PATCH /api/2.5/auctions/ef8ee87d4c8e4fe0950dfad142792817/questions/7c9385ceafc140c788115b218251bd5e?acc_token=2bf83e2d5c58424e83e48d3e6e3ed6b3
Authorization: Basic YnJva2VyOg==
Content-Type: application/json

{
  "data": {
    "answer": "Test answer"
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2018-11-06T15:15:20.046860+02:00", 
    "answer": "Test answer", 
    "id": "7c9385ceafc140c788115b218251bd5e", 
    "questionOf": "tender"
  }
}