GET /api/2.5/auctions/ae7d7760cfc046b6b8b89e437cb4e761/bids/9ca5e52078464c3a965cff9a86c344e5?acc_token=626e4c9969b94db0a42ef62c8c471f8a&data=status&data=qualified&data=bidNumber
Authorization: Basic YnJva2VyOg==


200 OK
Content-Type: application/json

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "укр.doc", 
        "url": "http://localhost/api/2.5/auctions/ae7d7760cfc046b6b8b89e437cb4e761/bids/9ca5e52078464c3a965cff9a86c344e5/documents/ac5452742f3146a99fcd9a74b36f5b1c?download=d24bd947343a4916a629234197853e1c", 
        "format": "application/msword", 
        "documentOf": "bid", 
        "datePublished": "2018-10-08T15:23:32.186567+03:00", 
        "documentType": "eligibilityDocuments", 
        "dateModified": "2018-10-08T15:23:32.186591+03:00", 
        "id": "ac5452742f3146a99fcd9a74b36f5b1c"
      }
    ], 
    "bidNumber": 1, 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-10-08T15:23:32.150424+03:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "9ca5e52078464c3a965cff9a86c344e5"
  }
}