POST /api/2.5/auctions/ae7d7760cfc046b6b8b89e437cb4e761/bids
Authorization: Basic YnJva2VyOg==
Content-Type: application/json

{
  "data": {
    "status": "draft", 
    "qualified": true, 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "01220", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "locality": "м. Київ"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json
Location: /api/2.5/auctions/ae7d7760cfc046b6b8b89e437cb4e761/bids/e8558a7961e344df9997ceeb9c0c3610

{
  "access": {
    "token": "9a246532dff84de8ada7a5c33169c1dd"
  }, 
  "data": {
    "owner": "broker", 
    "status": "draft", 
    "id": "e8558a7961e344df9997ceeb9c0c3610", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ]
  }
}