GET /api/2.5/auctions/ef8ee87d4c8e4fe0950dfad142792817
Authorization: Basic YXVjdGlvbjo=


200 OK
Content-Type: application/json

{
  "data": {
    "bankAccount": {
      "description": "Test Bank Account", 
      "accountIdentification": [
        {
          "scheme": "UA-EDR", 
          "id": "66113000-5", 
          "description": "Test"
        }
      ], 
      "bankName": "Test bank name"
    }, 
    "auctionID": "UA-EA-2018-09-20-000001", 
    "minNumberOfQualifiedBids": 2, 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/auctions/ef8ee87d4c8e4fe0950dfad142792817", 
    "enquiryPeriod": {
      "startDate": "2018-10-19T14:33:20.066118+02:00", 
      "endDate": "2018-11-05T20:00:00+02:00"
    }, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "ef8ee87d4c8e4fe0950dfad142792817", 
    "tenderPeriod": {
      "startDate": "2018-10-21T14:33:20.066118+02:00", 
      "endDate": "2018-11-02T20:00:00+02:00"
    }, 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "texas"
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "dateModified": "2018-11-06T14:33:20.039212+02:00", 
    "status": "active.auction", 
    "lotHolder": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "description": "test procuredure", 
    "auctionPeriod": {
      "startDate": "2018-11-06T14:33:20.066118+02:00", 
      "shouldStartAfter": "2018-11-06T00:00:00+02:00"
    }, 
    "procurementMethodType": "landlease", 
    "date": "2018-10-17T14:33:20.066118+02:00", 
    "budgetSpent": {
      "currency": "UAH", 
      "amount": 35, 
      "valueAddedTaxIncluded": true
    }, 
    "lotIdentifier": "219560", 
    "rectificationPeriod": {
      "startDate": "2018-10-19T14:33:20.066118+02:00", 
      "endDate": "2018-10-23T14:33:20.066118+02:00"
    }, 
    "contractTerms": {
      "type": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 42, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06110000-6", 
          "description": "Земельні ділянки"
        }, 
        "additionalClassifications": [
          {
            "scheme": "kvtspz", 
            "id": "01.04", 
            "description": "Test"
          }, 
          {
            "scheme": "cadastralNumber", 
            "id": "42", 
            "description": "Test"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "3e1b5bec9f3846eea93e02c70c95d693", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0001
      }
    ], 
    "procurementMethod": "open", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}