POST /api/2.5/auctions/ef8ee87d4c8e4fe0950dfad142792817/questions
Authorization: Basic YnJva2VyOg==
Content-Type: application/json

{
  "data": {
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність"
  }
}


201 Created
Content-Type: application/json
Location: /api/2.5/auctions/ef8ee87d4c8e4fe0950dfad142792817/questions/b1cc28d0329748a094464826069a7698

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "title": "Калорійність", 
    "date": "2018-11-06T14:33:30.195431+02:00", 
    "id": "b1cc28d0329748a094464826069a7698", 
    "questionOf": "tender"
  }
}