GET /api/2.5/auctions/ef8ee87d4c8e4fe0950dfad142792817/bids/8ef6c80be5f440329695167c7b81499b?acc_token=8fcf9c79ba8342b9b8a9a256489346f5
Authorization: Basic YnJva2VyOg==


200 OK
Content-Type: application/json

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "title": "укр.doc", 
        "url": "http://localhost/get/dd2c4773c24148bcafb37c15e48b788d?KeyID=172d32c8&Signature=SXQigJFdovYi%2F9VhVcZvgq%252BuPPwe37qsEfHgszqwAhC8fN6gH4ZQvJNagEAwHujmd%252BXDhDYXFWsiHW8v6fwrAg%253D%253D", 
        "format": "application/msword", 
        "documentOf": "bid", 
        "datePublished": "2018-11-06T14:33:20.036272+02:00", 
        "documentType": "eligibilityDocuments", 
        "dateModified": "2018-11-06T14:33:20.036272+02:00", 
        "id": "beff27f2339342b78124ac5db1ba8519"
      }
    ], 
    "bidNumber": 1, 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "8ef6c80be5f440329695167c7b81499b", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/ef8ee87d4c8e4fe0950dfad142792817?key_for_bid=8ef6c80be5f440329695167c7b81499b"
  }
}