PATCH /api/2.5/auctions/ae7d7760cfc046b6b8b89e437cb4e761/bids/9ca5e52078464c3a965cff9a86c344e5?acc_token=626e4c9969b94db0a42ef62c8c471f8a
Authorization: Basic YnJva2VyOg==
Content-Type: application/json

{
  "data": {
    "status": "pending"
  }
}


200 OK
Content-Type: application/json

{
  "data": {
    "status": "pending", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-10-08T15:23:31.973065+03:00", 
    "qualified": false, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "9ca5e52078464c3a965cff9a86c344e5"
  }
}