GET /api/2.5/auctions/ae7d7760cfc046b6b8b89e437cb4e761/bids/3021b2a3f475498b9bff3d58f605319f?acc_token=27213c33fd4146839f11f4227836a7bb
Authorization: Basic YnJva2VyOg==


200 OK
Content-Type: application/json

{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "owner": "broker", 
    "id": "3021b2a3f475498b9bff3d58f605319f", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/ae7d7760cfc046b6b8b89e437cb4e761?key_for_bid=3021b2a3f475498b9bff3d58f605319f"
  }
}