POST /api/2.5/auctions/ef8ee87d4c8e4fe0950dfad142792817/bids
Authorization: Basic YnJva2VyOg==
Content-Type: application/json

{
  "data": {
    "status": "draft", 
    "qualified": true, 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "01220", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "locality": "м. Київ"
        }
      }
    ]
  }
}


201 Created
Content-Type: application/json
Location: /api/2.5/auctions/ef8ee87d4c8e4fe0950dfad142792817/bids/2d9045ffe37f4c2b8a09db0bfbb0d281

{
  "access": {
    "token": "0b1527eaf3ca4c80a3124bcfee62a090"
  }, 
  "data": {
    "owner": "broker", 
    "status": "draft", 
    "id": "2d9045ffe37f4c2b8a09db0bfbb0d281", 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ]
  }
}