POST /api/2.5/auctions
Authorization: Basic YnJva2VyOg==
Content-Type: application/json

{
  "data": {
    "status": "draft", 
    "bankAccount": {
      "description": "Test Bank Account", 
      "accountIdentification": [
        {
          "scheme": "UA-EDR", 
          "id": "66113000-5", 
          "description": "Test"
        }
      ], 
      "bankName": "Test bank name"
    }, 
    "lotHolder": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "description": "test procuredure", 
    "contractTerms": {
      "type": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "lotIdentifier": "219560", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 42
    }, 
    "auctionPeriod": {
      "startDate": "2018-11-20"
    }, 
    "tenderAttempts": 1, 
    "title": "футляри до державних нагород", 
    "procurementMethodType": "landlease", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06110000-6", 
          "description": "Земельні ділянки"
        }, 
        "additionalClassifications": [
          {
            "scheme": "kvtspz", 
            "id": "01.04", 
            "description": "Test"
          }, 
          {
            "scheme": "cadastralNumber", 
            "id": "42", 
            "description": "Test"
          }
        ], 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0001
      }
    ], 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "budgetSpent": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 35
    }
  }
}


201 Created
Content-Type: application/json
Location: /api/2.5/auctions/91e3e7946529494389c69b74ff4bdf56

{
  "access": {
    "transfer": "a1786e07f1604e2daebed660d40955af", 
    "token": "7f9a013b46af452ea3528fbd89043be3"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-11-06-000001", 
    "minNumberOfQualifiedBids": 2, 
    "registrationFee": {
      "currency": "UAH", 
      "amount": 700.87
    }, 
    "submissionMethod": "electronicAuction", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "91e3e7946529494389c69b74ff4bdf56", 
    "guarantee": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionParameters": {
      "type": "texas"
    }, 
    "dateModified": "2018-11-06T14:33:24.274844+02:00", 
    "status": "draft", 
    "lotHolder": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "description": "test procuredure", 
    "auctionPeriod": {
      "startDate": "2018-11-20T00:00:00+02:00"
    }, 
    "procurementMethodType": "landlease", 
    "date": "2018-11-06T14:33:24.271809+02:00", 
    "lotIdentifier": "219560", 
    "contractTerms": {
      "type": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 42, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "06110000-6", 
          "description": "Земельні ділянки"
        }, 
        "additionalClassifications": [
          {
            "scheme": "kvtspz", 
            "id": "01.04", 
            "description": "Test"
          }, 
          {
            "scheme": "cadastralNumber", 
            "id": "42", 
            "description": "Test"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "8c602eba07104554b02a8fe77566e8b9", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.0001
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }
  }
}